app = "ai-trading-pro-lojgdrzk"
primary_region = "iad"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "15s"
  grace_period = "5s"
  method = "GET"
  path = "/api/health"
  protocol = "http"
  timeout = "10s"

[processes]
  app = "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:8080"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
